#!/bin/sh
# this tool generates plugins/BUILDS file for slimrat's update server

echo "# This file is used only if named BUILDS and placed on slimrat's update server in plugins folder.
# Every line contains plugin's filename and build number separated by whitespace(s)."

for file in *.pm
do
	echo $file `grep -P "##\s*BUILD" "$file" | sed -r 's/^.+BUILD\s*//'`
done
